name: EAS Android Build

on:
  workflow_dispatch:

jobs:
  build-android:
    name: 🎉 EAS Android Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Install EAS CLI
    - name: Install EAS CLI
      run: npm install -g eas-cli

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Log in to Expo using the access token
    - name: EAS login
      run: eas login --token Z-sZtJoYFZkXIkTxnkVHHn2HXt5Jncul-adljKi6

    # Build Android APK using EAS with the production profile
    - name: Build Android APK
      run: eas build --platform android --profile production

    # Upload APK to GitHub Release
    - name: Upload APK to GitHub Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.apk
        tag: v1.0
        overwrite: true
        body: "This is the first Android APK release built with EAS Build"
